replicaCount: 1
image:
  repository: "parity/polkadot"
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""
ingress:
  enabled: false
  host: test

service:
  port: 9615

node:
  name: ""
  chain: "polkadot"

resources: 
  limits:
    cpu: 2000m
    memory: 3000Mi
  requests:
    cpu: 100m
    memory: 110Mi

livenessProbe:
  enabled: false
  path: /health
  # path: /
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 4

readinessProbe:
  enabled: false
  path: /health
  # path: /
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5 
  successThreshold: 1
  failureThreshold: 3

prometheus:
  operator:
    enabled: true

# grafana:
#   service:
#     type: NodePort
#     nodePort: 31472
#     portName: grafana-np
