replicaCount: 1
image:
  repository: "parity/polkadot"
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""
ingress:
  enabled: false
  host: test

service:
  port: 9615

node:
  name: ""
  chain: "kusama"

resources: 
  limits:
    cpu: 1500m
    memory: 4000Mi
  requests:
    cpu: 100m
    memory: 110Mi

livenessProbe:
  enabled: false
  path: /health
  # path: /
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 4

readinessProbe:
  enabled: false
  path: /health
  # path: /
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5 
  successThreshold: 1
  failureThreshold: 3
