{{ if .Values.prometheus.operator.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: polkadot
  labels:
    app.kubernetes.io/name: {{ .Release.Name }} 
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  endpoints:
  - port: {{ .Release.Name }}
{{ end }}
